In [9]:
import numpy as np

arr = np.random.randint(1,51,(3,4))
print("Original array:")
print(f"{arr}")

mean = arr.mean()
median = np.median(arr)
stdeviation = arr.std()
print(f"Mean = {mean:.2f}\nMedian = {median:.2f}\nStandard Deviation = {stdeviation:.2f}")

print(f"Total sum = {arr.sum()}")
print(f"Sum of each row = {arr.sum(axis = 1)}")
print(arr.shape)
print(arr.reshape(2,6))

Original array:
[[26 45 26 15]
 [22 26 43 12]
 [ 4 21 33  9]]
Mean = 23.50
Median = 24.00
Standard Deviation = 12.09
Total sum = 282
Sum of each row = [112 103  67]
(3, 4)
[[26 45 26 15 22 26]
 [43 12  4 21 33  9]]


In [19]:
import numpy as np
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2 = np.array([[6,7,2],
                [9,3,1],
                [6,3,7]])
print(f"Arrar 1: \n{arr1}")
print(f"Arrar 2: \n{arr2}")

add = arr1 + arr2
print(add)

sub = arr1 - arr2
print(sub)

elemult = arr1 * arr2
dotmulti = np.dot(arr1, arr2)
print(elemult)
print(dotmulti)

trans1 = arr1.T
trans2 = arr2.T
print(trans1)
print(trans2)

deter1 = np.linalg.det(arr1)
deter2 = np.linalg.det(arr2)
print(deter1)
print(deter2)
if deter1 != 0:
    inva1 = np.linalg.inv(arr1)
    print(inva1)
else:
    print("Deter is 0")

if deter2 != 0:
    inva2 = np.linalg.inv(arr2)
    print(inva2)
else:
    print("Deter is 0")




Arrar 1: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Arrar 2: 
[[6 7 2]
 [9 3 1]
 [6 3 7]]
[[ 7  9  5]
 [13  8  7]
 [13 11 16]]
[[-5 -5  1]
 [-5  2  5]
 [ 1  5  2]]
[[ 6 14  6]
 [36 15  6]
 [42 24 63]]
[[ 42  22  25]
 [105  61  55]
 [168 100  85]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[6 9 6]
 [7 3 3]
 [2 1 7]]
0.0
-273.0
Deter is 0
[[-0.06593407  0.15750916 -0.003663  ]
 [ 0.20879121 -0.10989011 -0.04395604]
 [-0.03296703 -0.08791209  0.16483516]]
