In [1]:
import numpy as np

arr = np.random.randint(1,51,(3,4))
print(f"Original Array:\n{arr}\n")

print("Computations:\n")

print(f"Mean of array = {np.mean(arr):.2f}")
print(f"Median of array = {np.median(arr):.2f}")
print(f"Standard deviation of array = {np.std(arr):.2f}\n")

print(f"Sum of array = {arr.sum()}")
print(f"Sum of each row = {arr.sum(axis=1)}\n")

print(f"Dimension change of array: \n{arr.reshape(2,6)}")

Original Array:
[[16 41 43 14]
 [29 42  2 14]
 [39 13 25 46]]

Computations:

Mean of array = 27.00
Median of array = 27.00
Standard deviation of array = 14.35

Sum of array = 324
Sum of each row = [114  87 123]

Dimension change of array: 
[[16 41 43 14 29 42]
 [ 2 14 39 13 25 46]]


In [2]:
import numpy as np

mat1_info = []
for i in range(3):
    row = list(map(int,input(f"Enter row {i+1} for matrix 1 (3 no's, space separated): ").split()))
    mat1_info.append(row)

mat1 = np.array(mat1_info)

print(f"Matrix 1:\n{mat1}")

mat2_info = []
for i in range(3):
    row = list(map(int,input(f"Enter row {i+1} for matrix 2 (3 no's, space separated): ").split()))
    mat2_info.append(row)

mat2 = np.array(mat2_info)

print(f"Matrix 2:\n{mat2}\n")

print("----------------------")
print("      COMPUTATIONS    ")
print("----------------------")
print(f"Matrix addition:\n{np.add(mat1,mat2)}")
print(f"Matrix subtraction:\n{np.subtract(mat1,mat2)}")

print(f"Matrix element-wise multiplication:\n{(mat1*mat2)}")
print(f"Matrix dot product:\n{np.dot(mat1,mat2)}")

print(f"Transpose of Matrix 1:\n{mat1.T}")
print(f"Transpose of Matrix 2:\n{mat2.T}")

print(f"Determinant of Matrix 1:\n{np.linalg.det(mat1):.2f}")
print(f"Determinant of Matrix 2:\n{np.linalg.det(mat2):.2f}")

if np.linalg.det(mat1) != 0:
    print(f"Inverse of Matrix 1:\n{np.linalg.inv(mat1)}")
else:
    print("Inverse of Matrix 1 not possible!")

if np.linalg.det(mat2) != 0:
    print(f"Inverse of Matrix 2:\n{np.linalg.inv(mat2)}")
else:
    print("Inverse of Matrix 2 not possible!")

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2:
[[3 2 1]
 [6 8 3]
 [1 6 2]]

----------------------
      COMPUTATIONS    
----------------------
Matrix addition:
[[ 4  4  4]
 [10 13  9]
 [ 8 14 11]]
Matrix subtraction:
[[-2  0  2]
 [-2 -3  3]
 [ 6  2  7]]
Matrix element-wise multiplication:
[[ 3  4  3]
 [24 40 18]
 [ 7 48 18]]
Matrix dot product:
[[ 18  36  13]
 [ 48  84  31]
 [ 78 132  49]]
Transpose of Matrix 1:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of Matrix 2:
[[3 6 1]
 [2 8 6]
 [1 3 2]]
Determinant of Matrix 1:
0.00
Determinant of Matrix 2:
4.00
Inverse of Matrix 1 not possible!
Inverse of Matrix 2:
[[-0.5   0.5  -0.5 ]
 [-2.25  1.25 -0.75]
 [ 7.   -4.    3.  ]]
