In [34]:
import numpy as np

arr = np.random.randint(1,51,(3,4))
print(f"Original Array:\n{arr}\n")

print("Computations:\n")

print(f"Mean of array = {np.mean(arr):.2f}")
print(f"Median of array = {np.median(arr):.2f}")
print(f"Standard deviation of array = {np.std(arr):.2f}\n")

print(f"Sum of array = {arr.sum()}")
print(f"Sum of each row = {arr.sum(axis=1)}\n")

print(f"Dimension change of array: \n{arr.reshape(2,6)}")

Original Array:
[[42 39 23 45]
 [40 10 22 34]
 [13 15 47 13]]

Computations:

Mean of array = 28.58
Median of array = 28.50
Standard deviation of array = 13.38

Sum of array = 343
Sum of each row = [149 106  88]

Dimension change of array: 
[[42 39 23 45 40 10]
 [22 34 13 15 47 13]]


In [44]:
import numpy as np

mat1_info = []
for i in range(3):
    row = list(map(int,input(f"Enter row {i+1} for matrix 1 (3 no's, space separated): ").split()))
    mat1_info.append(row)

mat1 = np.array(mat1_info)

print(f"Matrix 1:\n{mat1}")

mat2_info = []
for i in range(3):
    row = list(map(int,input(f"Enter row {i+1} for matrix 2 (3 no's, space separated): ").split()))
    mat2_info.append(row)

mat2 = np.array(mat2_info)

print(f"Matrix 2:\n{mat2}\n")

print("----------------------")
print("      COMPUTATIONS    ")
print("----------------------")
print(f"Matrix addition:\n{np.add(mat1,mat2)}")
print(f"Matrix subtraction:\n{np.subtract(mat1,mat2)}")

print(f"Matrix element-wise multiplication:\n{(mat1*mat2)}")
print(f"Matrix dot product:\n{np.dot(mat1,mat2)}")

print(f"Transpose of Matrix 1:\n{mat1.T}")
print(f"Transpose of Matrix 2:\n{mat2.T}")

print(f"Determinant of Matrix 1:\n{np.linalg.det(mat1):.2f}")
print(f"Determinant of Matrix 2:\n{np.linalg.det(mat2):.2f}")

if np.linalg.det(mat1) != 0:
    print(f"Inverse of Matrix 1:\n{np.linalg.inv(mat1)}")
else:
    print("Inverse of Matrix 1 not possible!")

if np.linalg.det(mat2) != 0:
    print(f"Inverse of Matrix 2:\n{np.linalg.inv(mat2)}")
else:
    print("Inverse of Matrix 2 not possible!")

Matrix 1:
[[2 1 0]
 [1 2 1]
 [0 1 2]]
Matrix 2:
[[1 0 1]
 [0 1 1]
 [1 1 1]]

----------------------
      COMPUTATIONS    
----------------------
Matrix addition:
[[3 1 1]
 [1 3 2]
 [1 2 3]]
Matrix subtraction:
[[ 1  1 -1]
 [ 1  1  0]
 [-1  0  1]]
Matrix element-wise multiplication:
[[2 0 0]
 [0 2 1]
 [0 1 2]]
Matrix dot product:
[[2 1 3]
 [2 3 4]
 [2 3 3]]
Transpose of Matrix 1:
[[2 1 0]
 [1 2 1]
 [0 1 2]]
Transpose of Matrix 2:
[[1 0 1]
 [0 1 1]
 [1 1 1]]
Determinant of Matrix 1:
4.00
Determinant of Matrix 2:
-1.00
Inverse of Matrix 1:
[[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]
Inverse of Matrix 2:
[[ 0. -1.  1.]
 [-1.  0.  1.]
 [ 1.  1. -1.]]
