In [34]:
import numpy as np

arr = np.random.randint(1,51,(3,4))
print(f"Original Array:\n{arr}\n")

print("Computations:\n")

print(f"Mean of array = {np.mean(arr):.2f}")
print(f"Median of array = {np.median(arr):.2f}")
print(f"Standard deviation of array = {np.std(arr):.2f}\n")

print(f"Sum of array = {arr.sum()}")
print(f"Sum of each row = {arr.sum(axis=1)}\n")

print(f"Dimension change of array: \n{arr.reshape(2,6)}")

Original Array:
[[42 39 23 45]
 [40 10 22 34]
 [13 15 47 13]]

Computations:

Mean of array = 28.58
Median of array = 28.50
Standard deviation of array = 13.38

Sum of array = 343
Sum of each row = [149 106  88]

Dimension change of array: 
[[42 39 23 45 40 10]
 [22 34 13 15 47 13]]
