In [2]:
import numpy as np

arr = np.random.randint(1,51,(3,4))
print(f"Original Array:\n{arr}\n")

print("Computations:\n")

print(f"Mean of array = {np.mean(arr):.2f}")
print(f"Median of array = {np.median(arr):.2f}")
print(f"Standard deviation of array = {np.std(arr):.2f}\n")

print(f"Sum of array = {arr.sum()}")
print(f"Sum of each row = {arr.sum(axis=1)}\n")

print(f"Dimension change of array: \n{arr.reshape(2,6)}")

Original Array:
[[21 21 17 10]
 [ 7 16 30 40]
 [47 19 31 34]]

Computations:

Mean of array = 24.42
Median of array = 21.00
Standard deviation of array = 11.58

Sum of array = 293
Sum of each row = [ 69  93 131]

Dimension change of array: 
[[21 21 17 10  7 16]
 [30 40 47 19 31 34]]


In [3]:
import numpy as np

arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2 = np.array([[6,7,2],
                 [1,6,2],
                 [4,6,1]])
print(f"Arr 1:\n{arr1}")
print(f"Arr 2:\n{arr2}")

add = arr1+arr2
print(add)
sub = arr1 - arr2
print(sub)
elemul = arr1*arr2
print(elemul)
dotmul = np.dot(arr1,arr2)
print(dotmul)
trans1 = arr1.T
trans2 = arr2.T
print(trans1)
print(trans2)
deter1 = np.linalg.det(arr1)
deter2 = np.linalg.det(arr2)
if deter1 != 0:
    inv1 = np.linalg.inv(arr1)
    print(inv1)
else:
    print("Inverse not possible")
if deter2 != 0:
    inv2 = np.linalg.inv(arr2)
    print(inv2)
else:
    print("Inverse not possible!")
 

Arr 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Arr 2:
[[6 7 2]
 [1 6 2]
 [4 6 1]]
[[ 7  9  5]
 [ 5 11  8]
 [11 14 10]]
[[-5 -5  1]
 [ 3 -1  4]
 [ 3  2  8]]
[[ 6 14  6]
 [ 4 30 12]
 [28 48  9]]
[[ 20  37   9]
 [ 53  94  24]
 [ 86 151  39]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[6 1 4]
 [7 6 6]
 [2 2 1]]
Inverse not possible
[[ 0.26086957 -0.2173913  -0.08695652]
 [-0.30434783  0.08695652  0.43478261]
 [ 0.7826087   0.34782609 -1.26086957]]
