In [2]:
import pandas as pd

df = pd.read_csv("../datasets/sentiment.csv")
print(df["label"].value_counts())

label
1    5
0    5
Name: count, dtype: int64


In [10]:
import re

stop = set(["the","is","in","and","to","a","of"])
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]','',text)
    tokens = text.split()
    return [t for t in tokens if t not in stop]

print(preprocess("This is an example!")) 

['this', 'an', 'example']


In [21]:
import numpy as np
import pandas as pd
# a)
arr = np.random.randint(1,101,25)
matrix = arr.reshape(5,5)
print(matrix)
print()
print(matrix.sum(axis = 1))
print()
print(matrix.sum(axis=0))
print()
# b)
df = pd.DataFrame({
    "Name":["fattah","john","bob"],
    "Age":[67,32,21],
    "Marks":[98,43,89],
    "City":["Hum","Tum","Bam"]
})
print(df.iloc[0])
print(df.iloc[:,2])
print()
print(df.loc[0:1,"Marks"])



[[ 75  85  54  67  58]
 [ 81   2  51  77  98]
 [ 76   4  78  10  36]
 [ 28  59  19  25 100]
 [ 60  71  74  74  22]]

[339 309 204 231 301]

[320 221 276 253 314]

Name     fattah
Age          67
Marks        98
City        Hum
Name: 0, dtype: object
0    98
1    43
2    89
Name: Marks, dtype: int64

0    98
1    43
Name: Marks, dtype: int64
